NeuronActivation/kalja-xyz

flake.lock, package.json, pnpm-lock.yaml, postcss.config.js, src/app.css, src/routes/+layout.svelte, src/routes/+page.svelte, svelte.config.js, tailwind.config.js
Using [RippleUI](https://www.ripple-ui.com/) component library
=> Setup Tailwindcss and RippleUI component library

src/routes/+page.svelte
=> Event cards

.env
This should fix the incorrect path
=> Fix SvelteKit project paths on GitHub Pages environment

src/routes/+page.svelte, static/cards/english.json
In this pull request we are:
- Adding notice of uncompleted events at the end of the game.
- Changing text's of button's for last two cards.
- Fixing typo in the English data.
- Adding few comments.
=> Uncompleted events at the end of the game

static/cards/finnish.json
This pull request fixes a typo in card "Laimeinta juomaa juova juo".
=> Fixing typo in cards

.npmrc, .prettierignore, flake.nix, package.json, pnpm-lock.yaml, postcss.config.js, src/app.css, src/routes/+layout.svelte, src/routes/+page.svelte, tailwind.config.js
Some basic styling with PicoCSS components. Also enabled formatting for .svelte files – I forgot to include that earlier. Lots of changes, but that's just because of the formatting addition.
TLDR: added style tags and the player removal function.
=> Improve UI with PicoCSS Styling

static/cards/english.json, static/cards/finnish.json
- Remove "Memories or Fantasy".
- Change targetPlayer value of "Famous Quote".
=> Fixes to cardData

static/cards/finnish.json
Removed question "Kyllä tai ei".
Added questions "Sukkaralli", "Imitaattori", "Sanonta", "Dance king" and "Ootsä se...".
Fixed spelling on multiple questions.
=> Added 5 question, fixed spelling and removed one question

package.json, src/routes/+page.svelte
Randomize player order to added players before new game begins.
Upgrade pnpm dev dependency.
=> Randomize player order

src/routes/+page.svelte
Add functionality for preserving the game state and reset button.
=> Preserve game state

static/cards/english.json, static/cards/finnish.json
Added four new cards in finnish and english from index 79 to 82.
=> Added four new cards

src/lib/languages/load.ts, src/lib/managers/game.ts
Fix two bugs:
- Shuffling using only first 30 questions
- Endgame not working
=> Fix shuffling and endgame

static/cards/english.json, static/cards/finnish.json
Added four new cards in finnish and english from ID's 83 to 86
=> Add 4 new cards

src/lib/components/End.svelte, src/lib/components/Game.svelte, src/lib/stores/gameStore.ts, src/routes/+page.svelte, static/locales/english.json, static/locales/finnish.json
Really simple solution but seems to work. Closing #30 .
=> End.svelte and replay button

src/lib/components/Game.svelte, src/lib/components/Header.svelte, src/lib/components/icons/ReloadIcon.svelte, src/lib/languages/language.ts, src/lib/languages/load.ts, src/lib/stores/gameStore.ts, static/locales/english.json, static/locales/finnish.json
Ability to reroll any card at any given moment and then the game continues normally.
- New function `loadSingleCard` that draws a new card with same seed for all languages and updates the `languageData`.
- New helper function `getCardUrl`
- New locale "reroll"
- Small UI changes
Closes #33
=> Reroll a card

package.json, src/app.html, src/lib/components/Footer.svelte, src/lib/interfaces/metadata.ts, src/routes/+layout.svelte, static/locales/english.json, static/locales/finnish.json, static/robots.txt, static/sitemap.xml
Changed name from "Santerin Juomapeli v2" to "kalja.xyx".
=> Metadata and SEO improvements + Change name

.github/workflows/deploy.yml
Causes deployment to fail in [#a3dce68](https://github.com/NeuronActivation/kalja-xyz/actions/runs/13055362060/job/36424956591)
=> Bump actions/upload-pages-artifact to v3

.github/workflows/deploy.yml
This should finally fix the deployment after failed attempt in #53 
Tested in [jervw/kalja-xyz](https://github.com/jervw/kalja-xyz)
=> Bump actions/deploy-pages to v4.0.5 

src/lib/constants/isBrowser.ts, src/lib/languages/load.ts, src/lib/stores/gameStore.ts, src/lib/stores/languageStore.ts
Fixing the known bug where the game breaks when window is reloaded and then new card is rerolled.
Also a little refactoring in languageStore and gameStore.
Closes #50 .
=> Game breaks when reloading and then rerolling a card

src/lib/components/Game.svelte
=> Rerolled card restores after refresh

src/lib/components/End.svelte, src/lib/stores/gameStore.ts
=> Replay starts the very same game

src/lib/components/Header.svelte, src/lib/components/Lobby.svelte, src/lib/constants/applicationState.ts, src/lib/constants/isBrowser.ts, src/lib/interfaces/card.ts, src/lib/interfaces/gameEvent.ts, src/lib/interfaces/gameState.ts, src/lib/interfaces/metadata.ts, src/lib/interfaces/player.ts, src/lib/languages/language.ts, src/lib/languages/load.ts, src/lib/managers/game.ts, src/lib/stores/gameStore.ts, src/lib/stores/languageStore.ts, src/lib/utils/seed.ts, src/lib/utils/storage.ts, src/routes/+layout.ts
Adding TSDoc comments to functions, enums, interfaces and exported types.
Also little refactoring:
- `playerName` should not be part of the `GameState`.
- `storedData` is unnecessary variable in `load.ts`.
- `createLanguageStore()` returns documented interface instead of an object.
- Fetch function is unnecessary parameter in couple of functions.
Closes #37
=> TSDoc + refactoring

src/lib/components/Game.svelte, src/lib/components/Header.svelte
**Fixed following issues:**
- Event end text doesn't align correctly with smaller screen sizes
- Adjusted event text size from h1 to h2
- WebKit: Language button label aligned properly
Let me know if there is anything else
Closes #68
=> Improve responsiveness

src/lib/components/Lobby.svelte
=> Close settings menu by default

src/lib/components/Game.svelte, src/lib/components/Lobby.svelte, src/lib/interfaces/card.ts, src/lib/interfaces/gameState.ts, src/lib/languages/load.ts, src/lib/managers/game.ts
- Fixed a couple of typos in the comments.
- Changed the "cardAmount" from default value to possibly undefined type.
=> Fixing typos in comments

src/lib/languages/load.ts, static/cards/cards.json
=> Remove "targetPlayer" and "timedEvent" from "cards.json"

static/cards/cards.json
- Added tag "physical" to the card "Take a Picture of Your Feet". This card *could* be played in "non-physical" context, but it simply does not work there. 
- Rewrote the descriptions of the card "Story".
=> Fixes to card data

src/lib/constants/tag.ts, static/cards/cards.json, static/locales/english.json, static/locales/finnish.json
Waiting for #91 to be merged to mark card number 118 with "finland" tag.
=> Tag for Finland specific cards

src/lib/components/Game.svelte, src/lib/interfaces/gameState.ts, src/lib/interfaces/player.ts, src/lib/managers/game.ts, src/lib/stores/gameStore.ts
Please tests thoroughly. This is a very delicate part of this program. Closes #88
=> Rerolled event cards are not stopped correctly

src/lib/cards/createCards.ts
"base" is deprecated, I need this fixed for something else
=> Remove deprecated "base"
